- name: Machine Credentail to connect to workstation using openstack.pub
  tower_credential:
    name:           "{{ item.name }}"
    organization:   "{{ org_name }}"
    state:          present
    kind:           ssh
    tower_host:     "{{ host_tower }}"
    tower_username: "{{ user_name }}"
    tower_password: "{{ password }}"
    tower_verify_ssl: no
    ssh_key_data:   "{{ item.ssh_key }}"
    username:       "{{ item.username }}"
  loop:
    - { name: "{{ ssh_cred_name }}", ssh_key: "{{ user_cred_path }}", username: "{{ user_cred_name }}" }
    - { name: "{{ opentlc_cred_name }}", ssh_key: "{{ opentlc_cred_path }}", username: "{{ opentlc_login }}" }
    

- name: Create Homework Assignment project
  tower_project:
    name:           "{{ proj_name }}"
    description:    "{{ proj_descr }} "
    organization:   "{{ org_name }}"
    state:          present

- name: Create Inventory
  tower_inventory:
    name:           "{{ static_inventory_name }}"
    organization:   "{{ org_name }}"
    state:          present

- name: Create Group in static inventory 
  tower_group:
      name:         "{{ group_name }}"
      inventory:    "{{ static_inventory_name }}"
      state:        present


- name: Add tower host
  tower_host:
    name:           "{{host_name}}"
    description:    "workstation"
    inventory:      "{{static_inventory_name}}"
    state:          present

- name: Associate workstation host to group
  command: | 
    tower-cli host associate --host "{{host_name}}" --group "{{group_name}}"


- name: Remove secret
  file:
    name: /root/secret.pem
    state: absent

